name: Example Workflow


jobs:
  create_folder:
    runs-on: self-hosted

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Create Folder
       run: |
          mkdir hello
          dir
