name: Example Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Create Folder
        run: |
          mkdir hello
          ls -l
